- name: install samba package
  tags: samba,fileserver
  package:
    name: samba
    state: latest

- name: start and enable samba service
  tags: samba,fileserver
  service:
    name: smb
    state: started
    enabled: yes