---

- hosts: all
  become: true
  tasks:

  # Install Apache and PHP using package manager
  - name: install Apache and PHP
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
  # Copy the index.html file to the web server root directory for CentOS and RedHat
  - name: copy html file for site
    copy:
      src: /home/saintdominicci/ansible-playbooks/files/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution in ['CentOS', 'RedHat']
  # Start the Apache service for CentOS and RedHat
  - name: start apache2 service
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution in ['CentOS', 'RedHat']
...