---

- hosts: all
  become: true
  tasks:

  # Install Apache and PHP using package manager on Debian and Ubuntu
  - name: install Apache and PHP for Debian and Ubuntu
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ['Debian', 'Ubuntu']

  # Install Apache and PHP using package manager on CentOS and RedHat
  - name: install Apache and PHP for CentOS and RedHat
    package:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ['CentOS', 'RedHat']

  # Copy the default_site.html file to the web server root directory
  - name: copy html file for site
    tags: apache,apache2,httpd
    copy:
      src: /home/saintdominicci/ansible-playbooks/files/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  # Start the Apache service for CentOS and RedHat
  - name: start apache2 service
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution in ['CentOS', 'RedHat']
...