---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == 'CentOS'

  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == 'CentOS'
  
  - name: start apache2 service
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == 'CentOS'

  # - name: copy html file for site
  #   copy:
  #     src: /files/index.html
  #     dest: /var/www/html/index.html
  #     owner: root
  #     group: root
  #     mode: 0644

  - name: add PHP support for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == 'CentOS'

  - name: ensure a list of packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - httpd
      - httpd-tools
    when: ansible_distribution == 'CentOS'
...