---

- hosts: all
  become: true
  tasks:

# CentOS
  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution in ['CentOS', 'RedHat']

  - name: install apache2 and PHP packages for CentOS/RedHat
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == 'CentOS'

  - name: copy html file for site
    copy:
      src: /home/saintdominicci/ansible-playbooks/files/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == 'CentOS'

  - name: start apache2 service
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == 'CentOS'

# Debian
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - name: install apache2 and PHP packages for Debian/Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ['Debian', 'Ubuntu']
...