---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS and RedHat)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ['CentOS', 'RedHat']

  - name: install updates (Debian and Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ['Debian', 'Ubuntu']


- hosts: web_servers
  become: true
  tasks:

  # Install Apache and PHP using package manager on Debian and Ubuntu
  - name: install Apache and PHP for Debian and Ubuntu
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ['Debian', 'Ubuntu']

  # Install Apache and PHP using package manager on CentOS and RedHat
  - name: install Apache and PHP for CentOS and RedHat
    package:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ['CentOS', 'RedHat']

  # Copy the index.html file to the web server root directory for CentOS and RedHat
  - name: copy html file for site
    copy:
      src: /home/saintdominicci/ansible-playbooks/files/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution in ['CentOS', 'RedHat']
  # Start the Apache service for CentOS and RedHat
  - name: start apache2 service
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution in ['CentOS', 'RedHat']

- hosts: db_servers
  become: true
  tasks:

  - name: install PostgreSQL database package (Debian and Ubuntu)
    apt:
      name: postgresql
      state: latest
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - name: install PostgreSQL database package (CentOS and RedHat)
    yum:
      name: postgresql
      state: latest
    when: ansible_distribution in ['CentOS', 'RedHat']
...