---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS and RedHat)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ['CentOS', 'RedHat']

  - name: install updates (Debian and Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ['Debian', 'Ubuntu']


- hosts: web_servers
  become: true
  tasks:

  # Install Apache and PHP using package manager on Debian and Ubuntu
  - name: install Apache and PHP for Debian and Ubuntu
    tags: apache,apache2,debian
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ['Debian', 'Ubuntu']

  # Install Apache and PHP using package manager on CentOS and RedHat
  - name: install Apache and PHP for CentOS and RedHat
    tags: apache,httpd,centos
    package:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ['CentOS', 'RedHat']

  # Copy the index.html file to the web server root directory for CentOS and RedHat
  - name: copy default html file for site
    tags: apache,httpd,centos
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 #set permissions of the file
    when: ansible_distribution in ['CentOS', 'RedHat']

  # Start the Apache service for CentOS and RedHat
  - name: start apache2 service
    tags: apache,httpd,centos
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution in ['CentOS', 'RedHat']

- hosts: db_servers
  become: true
  tasks:

  - name: install PostgreSQL database package (Debian and Ubuntu)
    tags: postgres,postgresql,db,debian
    apt:
      name: postgresql
      state: latest
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - name: install PostgreSQL database package (CentOS and RedHat)
    tags: postgres,postgresql,db,centos
    yum:
      name: postgresql
      state: latest
    when: ansible_distribution in ['CentOS', 'RedHat']

# Install file server package
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba,fileserver
    package:
      name: samba
      state: latest
...