---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (CentOS and RedHat)
    tags: always
    yum:
      update_cache: yes
    changed_when: false  # control over what is considered a change
    when: ansible_distribution in ['CentOS', 'RedHat']

  - name: update repository index (Debian and Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ['Debian', 'Ubuntu']

- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

# Install file server package
- hosts: file_servers
  become: true
  roles:
    - file_servers

...