- name: add ssh key to Albert user
  tags: always
  authorized_key:
    user: albert
    key: "{{ lookup('file', '/home/saintdominicci/.ssh/ansible.pub') }}"

- name: generate ssh_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd